---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE(cloudnull): These methods have been changed to use the rsync command
#  instead of the Synchronize module. The change was required due to an upstream
#  issue with the module when running with delegate_to and become. Sadly the fix
#  does not seem to be trivial. "https://github.com/ansible/ansible/issues/15405"
- name: "Get swift rings"
  command: |
    rsync -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' \
          -avz {{ swift_system_user_name }}@{{ hostvars[groups['swift_hosts'][0]]['ansible_host'] }}:/etc/swift/ring_build_files/ \
          /etc/swift/
  become: yes
  become_user: "{{ swift_system_user_name }}"

- name: "Get swift rings for backup in ring_build_files directory"
  command: |
    rsync -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' \
          -avz {{ swift_system_user_name }}@{{ hostvars[groups['swift_hosts'][0]]['ansible_host'] }}:/etc/swift/ring_build_files/ \
          /etc/swift/ring_build_files/
  become: yes
  become_user: "{{ swift_system_user_name }}"
