- name: Install Magnum server
  hosts: magnum_all
  user: root
  roles:
    - { role: "os_magnum", tags: [ "os-magnum" ] }
  vars:
    magnum_galera_address: "{{ internal_lb_vip_address }}"
    magnum_galera_database_name: magnum_service
    magnum_galera_user: magnum
    magnum_rabbitmq_userid: magnum
    magnum_rabbitmq_vhost: /magnum
    ansible_hostname: "{{ container_name }}"
    is_metal: "{{ properties.is_metal|default(false) }}"
