---
# Copyright 2015, Serge van Ginderachter <serge@vanginderachter.be>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# look for 1 ceph monitor host that is up
- name:           Verify Ceph monitors are up
  # using netcat instead of wait_for allows to both check the rc and the
  # output, rc not being available using wait_for + failed_when: false
  # failed_when: false  is needed to not loose any hosts, as this check expects
  # some to be down.
  local_action:   command nc -w 1 {{ item }} 22
  with_items:     "{{ ceph_mons }}"
  changed_when:   false
  failed_when:    false
  register:       ceph_mon_upcheck
  tags:
  - ceph-config-create-config
  - ceph-auth-client-keyrings
  - ceph-auth-nova-libvirt-secret

- name:           Set ceph_mon_host to an online monitor host
  set_fact:
                  ceph_mon_host: '{{ item.item }}'
  when:           item.rc == 0 and "OpenSSH" in item.stdout
  with_items:     "{{ ceph_mon_upcheck.results }}"
  tags:
  - ceph-config-create-config
  - ceph-auth-client-keyrings
  - ceph-auth-nova-libvirt-secret
