---
features:
  - Horizon now has the ability to set arbitrary configuration options using
    global option ``horizon_config_overrides`` in YAML format. The overrides
    follow the same pattern found within the other OpenStack service
    overrides. `General documentation on overrides can be found here <http://docs.openstack.org/developer/openstack-ansible/install-guide/configure-openstack.html#overriding-openstack-configuration-defaults>`_.
