---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Check if credential keys already exist
  stat:
    path: "{{ keystone_credential_key_repository }}/0"
  register: _credential_keys

- name: Create credential keys for Keystone
  command: >
    {{ keystone_bin }}/keystone-manage credential_setup
                                       --keystone-user "{{ keystone_system_user_name }}"
                                       --keystone-group "{{ keystone_system_group_name }}"
  become: yes
  become_user: "{{ keystone_system_user_name }}"
  when: not _credential_keys.stat.exists

- name: Ensure newest key is used for credential in Keystone
  command: >
    {{ keystone_bin }}/keystone-manage credential_migrate
                                       --keystone-user "{{ keystone_system_user_name }}"
                                       --keystone-group "{{ keystone_system_group_name }}"
  become: yes
  become_user: "{{ keystone_system_user_name }}"
  when: _credential_keys.stat.exists

- name: Rotate credential keys for Keystone
  command: >
    {{ keystone_bin }}/keystone-manage credential_rotate
                                       --keystone-user "{{ keystone_system_user_name }}"
                                       --keystone-group "{{ keystone_system_group_name }}"
  become: yes
  become_user: "{{ keystone_system_user_name }}"
  when: _credential_keys.stat.exists
