---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include: aodh_install_apt.yml
  static: no
  when:
    - ansible_pkg_mgr == 'apt'

- name: Create developer mode constraint file
  copy:
    dest: "/opt/developer-pip-constraints.txt"
    content: |
      {% for item in aodh_developer_constraints %}
      {{ item }}
      {% endfor %}
  when: aodh_developer_mode | bool

- name: Install requires pip packages
  pip:
    name: "{{ aodh_requires_pip_packages | join(' ') }}"
    state: latest
    extra_args: >-
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2

- name: Attempt venv download
  get_url:
    url: "{{ aodh_venv_download_url }}"
    dest: "/var/cache/{{ aodh_venv_download_url | basename }}"
    checksum: "sha1:{{ lookup('url', aodh_venv_download_url | replace('tgz', 'checksum')) }}"
  register: aodh_get_venv
  when: not aodh_developer_mode | bool

- name: Remove existing venv
  file:
    path: "{{ aodh_bin | dirname }}"
    state: absent
  when: aodh_get_venv | changed

- name: Create aodh venv dir
  file:
    path: "{{ aodh_bin | dirname }}"
    state: directory
  register: aodh_venv_dir
  when:
    - not aodh_developer_mode | bool
    - aodh_get_venv | changed

- name: Unarchive pre-built venv
  unarchive:
    src: "/var/cache/{{ aodh_venv_download_url | basename }}"
    dest: "{{ aodh_bin | dirname }}"
    copy: "no"
  when:
    - not aodh_developer_mode | bool
    - aodh_get_venv | changed or aodh_venv_dir | changed
  notify: Restart aodh services

- name: Install pip packages
  pip:
    name: "{{ aodh_pip_packages | join(' ') }}"
    state: latest
    virtualenv: "{{ aodh_bin | dirname }}"
    virtualenv_site_packages: "no"
    extra_args: >-
      {{ aodh_developer_mode | ternary('--constraint /opt/developer-pip-constraints.txt', '') }}
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  when: aodh_developer_mode | bool
  notify: Restart aodh services

- name: Update virtualenv path
  command: >
    virtualenv-tools --update-path=auto --reinitialize {{ aodh_bin | dirname }}
  when:
    - not aodh_developer_mode | bool
    - aodh_get_venv | changed or aodh_venv_dir | changed
