---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Set fact to ignore cluster state
  set_fact:
    galera_ignore_cluster_state: true
  tags:
    - galera-upgrade

- name: Stop MariaDB
  service:
    name: mysql
    state: stopped
  register: galera_restart_fall_back
  until: galera_restart_fall_back | success
  retries: 3
  delay: 5
  tags:
    - galera-upgrade

- name: Find old sources
  shell: |
    grep -rnil maria /etc/apt/sources.list.d/*
  register: old_sources
  tags:
    - galera-upgrade
    - galera-apt-packages

- name: Remove old sources
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ old_sources.stdout_lines | default([]) }}"
  tags:
    - galera-upgrade
    - galera-apt-packages

- name: Update apt sources (Forced)
  apt:
    update_cache: yes
    cache_valid_time: 0
  register: apt_update
  until: apt_update|success
  retries: 5
  delay: 2
  when:
    - ansible_pkg_mgr == 'apt'
  tags:
    - galera-upgrade
    - galera-apt-packages

- name: UN-Install galera-server package
  apt:
    pkg: "mariadb-galera-server*"
    state: absent
  when:
    - ansible_pkg_mgr == 'apt'
  tags:
    - galera-upgrade
    - galera-apt-packages
