---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- include: galera_client_install_apt.yml
  when:
    - ansible_pkg_mgr == 'apt'
  tags:
    - install-apt

- include: galera_client_install_yum.yml
  when:
    - ansible_pkg_mgr == 'yum'
  tags:
    - install-yum

- name: inserted by bhujay for upgrading packaing to 16.8 before pip package install, it failed for MSSQL
  apt:
    name: packaging==16.8
    state: present


- name: Install pip packages
  pip:
    name: "{{ galera_client_pip_packages | join(' ') }}"
    state: latest
    extra_args: >-
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  tags:
    - galera-client-pip-packages

- name: inserted by bhujay revert back packaing to 16.7 pip installation of  MSSQL
  apt:
    name: packaging==16.7
    state: present    