---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Remove self signed cert for regen
  file:
    dest: "{{ rabbitmq_ssl_cert }}"
    state: "absent"
  when: rabbitmq_ssl_self_signed_regen | bool
  tags:
    - rabbitmq-ssl

# See playbooks/roles/rabbitmq_server/defaults/main.yml to provide custom
# subject material for certificates or specify a user-provided certificate and
# key pair.
- name: Create self-signed ssl cert
  command: >
    openssl req -new -nodes -sha256 -x509 -subj
    "{{ rabbitmq_ssl_self_signed_subject }}"
    -days 3650
    -keyout {{ rabbitmq_ssl_key }}
    -out {{ rabbitmq_ssl_cert }}
    -extensions v3_ca
    creates={{ rabbitmq_ssl_cert }}
  tags:
    - rabbitmq-ssl

- name: Ensure rabbitmq user owns the self-signed key and certificate
  file:
    path: "{{ item }}"
    owner: rabbitmq
    group: rabbitmq
  with_items:
    - "{{ rabbitmq_ssl_key }}"
    - "{{ rabbitmq_ssl_cert }}"
  tags:
    - rabbitmq-ssl
