---
# handlers file for openstack-ansible-magnum
- name: Restart magnum services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - "{{ magnum_api_program_name }}"
    - "{{ magnum_conductor_program_name }}"
